### ISSUE TITLE
Cannot find module 'uglifyify' from ...

### ISSUE THREAD

**Issue by pps83** [hughsk/uglifyify#47]
I installed browserify and uglifyify but the moment I mention uglifyify on command line I get an error.

> C:\test\test-require>browserify -t uglifyify --debug compress.js
Error: Cannot find module 'uglifyify' from 'C:\test\test-require'
    at C:\Users\test-user\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\test-user\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\test-user\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\test-user\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\test-user\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\test-user\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

compress.js is a simple dummy js file that require's another simple dummy js file.

**Comment by yoshuawuyts** [comment]
could you try installing `uglifyify` in the local directory instead of global, and try running it again?

**Comment by pps83** [comment]
Yep, when installed locally it works. Seems like a bug?

**Comment by yoshuawuyts** [comment]
Though I agree it might be confusing, it works as expected.
