### ISSUE TITLE
--ignore flag being ignored in Jenkins environment

### ISSUE THREAD

**Issue by Kalvin126** [hughsk/uglifyify#83]
Using `3.0.2`,

I am running: 

```Shell
./node_modules/.bin/browserify                                                  \
    --exclude crypto                                                            \
    --exclude util                                                              \
    --transform folderify                                                       \
    --entry ./node_modules/*****-*****-sdk/build/index.js                   \
    --entry ./node_modules/*****-*****-app/build/index.js                   \
    --outfile resources/*****-modules.js                                    \
    --ignore ./node_modules/*****-*****/build/lib/*****.js   \
    --ignore ./node_modules/*****-*****-sdk/build/lib/*****js      \
    --global-transform [ uglifyify --ignore '**/node_modules/*****-*****/**' --ignore '**/node_modules/*****-*****/**' ]
```

in a Jenkins pipeline environment. 

The two paths I want ignored are not actually getting ignored. If I run the same command locally through terminal, it actually does ignore the two paths. Does anyone know what could be the issue? Could it possibly be a bash issue? Jenkins? Shell?

**Comment by Kalvin126** [comment]
@danfinlay unfortunately #62 does not fix my issue 😕 I now encounter a crash: 

```
[20:57:38]: ▸ DefaultsError: `ignore` is not a supported option while parsing file: ***/node_modules/***-sdk/build/index.js
[20:57:38]: ▸ at DefaultsError.Object.defineProperty.get (eval at <anonymous> (***/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)
[20:57:38]: ▸ at Readable.errorExit (***/node_modules/browserify/bin/cmd.js:68:26)
[20:57:38]: ▸ at emitOne (events.js:77:13)
[20:57:38]: ▸ at Readable.emit (events.js:169:7)
[20:57:38]: ▸ at Labeled.<anonymous> (***/node_modules/read-only-stream/index.js:27:44)
[20:57:38]: ▸ at emitOne (events.js:77:13)
[20:57:38]: ▸ at Labeled.emit (events.js:169:7)
[20:57:38]: ▸ at Labeled.<anonymous> (***/node_modules/stream-splicer/index.js:133:18)
[20:57:38]: ▸ at emitOne (events.js:82:20)
[20:57:38]: ▸ at Labeled.emit (events.js:169:7)
```

**Comment by Kalvin126** [comment]
ah yes, as described in https://github.com/hughsk/uglifyify/issues/73, `ignore` flag looks to be broken in `4.0.0 +`
